#pragma once


#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define CODE_GLYPH_WIDTH 12
#define CODE_GLYPH_HEIGHT 12

#define STRATAGEM_ITEM_HEIGHT 32

#define MIN_STRATAGEMS_PER_ROUND 4
#define MAX_STRATAGEMS_PER_ROUND 10
#define MAX_STRATEGEM_SHUFFLE_RETRIES 5

#define ROUND_TIME_SECONDS 30
#define INVALID_CODE_DELAY 300

