#pragma once


#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define MIN_STRATAGEMS_PER_ROUND 5
#define MAX_STRATAGEMS_PER_ROUND 20
#define MAX_STRATEGEM_SHUFFLE_RETRIES 5

#define ROUND_TIME_SECONDS 30
