#!/usr/bin/env python3
# 生成中文字符的 XBM 位图头文件,供 Flipper Zero canvas_draw_xbm 使用
from PIL import Image, ImageDraw, ImageFont

# 中文文本(同时含中英文标点)
text = "你好,世界!"
font_path = "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"
font = ImageFont.truetype(font_path, 16)

# 测量实际占用的边界框
bbox = font.getbbox(text)
ox, oy = bbox[0], bbox[1]
w = bbox[2] - bbox[0]
h = bbox[3] - bbox[1]

# 渲染为 1-bit 位图(黑底白字 -> 1 表示笔画)
img = Image.new("1", (w, h), 0)
draw = ImageDraw.Draw(img)
draw.text((-ox, -oy), text, fill=1, font=font)

pixels = img.load()

# 按 XBM 标准打包:每字节8像素,LSB=最左像素,行优先
bytes_per_row = (w + 7) // 8
data = bytearray()
for y in range(h):
    for bcol in range(bytes_per_row):
        byte = 0
        for bit in range(8):
            x = bcol * 8 + bit
            if x < w and pixels[x, y]:
                byte |= (1 << bit)
        data.append(byte)

# 写出 C 头文件
with open("/workspace/hello_zh.h", "w") as f:
    f.write("// Auto-generated by gen_bitmap.py - DO NOT EDIT\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define ZH_W {w}\n")
    f.write(f"#define ZH_H {h}\n")
    f.write("static const uint8_t zh_bitmap[] = {\n    ")
    for i, v in enumerate(data):
        f.write(f"0x{v:02x},")
        if (i + 1) % 16 == 0:
            f.write("\n    ")
    f.write("\n};\n")

print(f"bitmap: {w}x{h}, {len(data)} bytes -> hello_zh.h")
