#include "uk_mbirth_sonicare.h"
#include <dolphin/dolphin.h>

/* generated by fbt from .png files in images folder */
#include <uk_mbirth_sonicare_icons.h>


static bool sonicare_debug_custom_event_callback(void* context, uint32_t event) {
    furi_assert(context);
    Sonicare* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, event);
}

static bool sonicare_debug_back_event_callback(void* context) {
    furi_assert(context);
    Sonicare* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

static Sonicare* sonicare_alloc(void) {
    Sonicare* sonicare = malloc(sizeof(Sonicare));
    
    sonicare->storage = furi_record_open(RECORD_STORAGE);
    sonicare->dialogs = furi_record_open(RECORD_DIALOGS);
    
    sonicare->view_dispatcher = view_dispatcher_alloc();
    sonicare->scene_manager = scene_manager_alloc(&sonicare_scene_handlers, sonicare);
    view_dispatcher_set_event_callback_context(sonicare->view_dispatcher, sonicare);
    view_dispatcher_set_custom_event_callback(sonicare->view_dispatcher, sonicare_debug_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(sonicare->view_dispatcher, sonicare_debug_back_event_callback);
    
    // Open GUI record
    sonicare->gui = furi_record_open(RECORD_GUI);
    
    // Open Notification record
    sonicare->notifications = furi_record_open(RECORD_NOTIFICATION);
    
    // Submenu
    sonicare->submenu = submenu_alloc();
    view_dispatcher_add_view(
        sonicare->view_dispatcher, SonicareViewSubmenu, submenu_get_view(sonicare->submenu));
    
    return sonicare;
}

static void sonicare_free(Sonicare* sonicare) {
    furi_assert(sonicare);
    
    // Submenu
    view_dispatcher_remove_view(sonicare->view_dispatcher, SonicareViewSubmenu);
    submenu_free(sonicare->submenu);
    
    view_dispatcher_free(sonicare->view_dispatcher);
    
    scene_manager_free(sonicare->scene_manager);
    
    furi_record_close(RECORD_GUI);
    sonicare->gui = NULL;
    
    furi_record_close(RECORD_NOTIFICATION);
    sonicare->notifications = NULL;
    
    furi_record_close(RECORD_STORAGE);
    furi_record_close(RECORD_DIALOGS);
    
    free(sonicare);
}

int32_t sonicare_app(void* p) {
    Sonicare* app = sonicare_alloc();
    UNUSED(p);
    //char* args = p;
    
    view_dispatcher_attach_to_gui(
        app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, SonicareSceneStart);

    view_dispatcher_run(app->view_dispatcher);
    
    sonicare_free(app);
    
    return 0;
}
