#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>

/* generated by fbt from .png files in images folder */
#include <uk_mbirth_sonicare_icons.h>

typedef struct {
  FuriMessageQueue* input_queue;
  ViewPort* view_port;
  Gui* gui;
} Sonicare;

void draw_callback(Canvas* canvas, void* context) {
    UNUSED(context);
    
    canvas_clear(canvas);
    canvas_set_color(canvas, ColorBlack);
    canvas_set_font(canvas, FontPrimary);
    
    canvas_draw_str_aligned(canvas, 1, 0, AlignLeft, AlignTop, "Sonicare");

    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str_aligned(canvas, 1, 14, AlignLeft, AlignTop, "Hello world!");
    
    canvas_set_font(canvas, FontKeyboard);
    canvas_draw_str_aligned(canvas, 1, 28, AlignLeft, AlignTop, "by mbirth.uk");
}

void input_callback(InputEvent* event, void* context) {
    Sonicare* app = context;
    furi_message_queue_put(app->input_queue, event, 0);
}

int32_t uk_mbirth_sonicare_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm uk_mbirth_sonicare!");
    Sonicare app;
    
    // Alloc
    app.view_port = view_port_alloc();
    app.input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    // Callbacks    
    view_port_draw_callback_set(app.view_port, draw_callback, &app);
    view_port_input_callback_set(app.view_port, input_callback, &app);
    
    // GUI
    app.gui = furi_record_open("gui");
    gui_add_view_port(app.gui, app.view_port, GuiLayerFullscreen);
    
    // Input handling
    InputEvent input;
    uint8_t exit_loop = 0;
    
    while (1) {
        furi_check(furi_message_queue_get(app.input_queue, &input, FuriWaitForever) == FuriStatusOk);
        
        switch (input.key) {
            case InputKeyLeft:
            case InputKeyRight:
            case InputKeyOk:
            case InputKeyUp:
            case InputKeyDown:
            case InputKeyBack:
                exit_loop = 1;
                break;
            default:
                break;
        }
        
        if (exit_loop) {
            break;
        }
        
        view_port_update(app.view_port);
    }
    
    // Free structs
    view_port_enabled_set(app.view_port, false);
    gui_remove_view_port(app.gui, app.view_port);
    furi_record_close("gui");
    view_port_free(app.view_port);
    
    return 0;
}

