#!/usr/bin/env python3
"""Extract RPCS3's Infinity base code, unmodified, into a C++ include for tests.

usage: extract_ref.py <rpcs3 repo root> <out.inc>

Pulled verbatim from RPCS3 (GPL-2.0-only), used only as the reference oracle:
  - infinity_figure / infinity_base class and member functions (Infinity.h/.cpp)
  - the command dispatch switch (usb_device_infinity::interrupt_transfer)
  - infinity_crc32 and the blank-figure creation code (infinity_dialog.cpp)
"""
import re
import sys

root, out_path = sys.argv[1], sys.argv[2]
read = lambda p: open(f"{root}/{p}", encoding="utf-8").read()

header = read("rpcs3/Emu/Io/Infinity.h")
source = read("rpcs3/Emu/Io/Infinity.cpp")
dialog = read("rpcs3/rpcs3qt/infinity_dialog.cpp")


def between(text, start, end):
    a = text.index(start)
    b = text.index(end, a)
    return text[a:b]


class_text = between(header, "struct infinity_figure", "extern infinity_base g_infinitybase;")
methods_text = between(
    source,
    "static constexpr std::array<u8, 32> SHA1_CONSTANT",
    "usb_device_infinity::usb_device_infinity(",
)
switch_text = between(source, "switch (command)", "m_queries.push(q_result);")
crc_text = between(dialog, "u32 infinity_crc32(", "figure_creator_dialog::figure_creator_dialog(")
blank_decl = re.search(
    r"static constexpr std::array<u8, 16> BLANK_BLOCK = \{.*?\};", dialog, re.S
).group(0)

create_start = dialog.index("std::array<u8, 0x14 * 0x10> file_data{};")
last_memcpy = dialog.index("memcpy(&file_data[16 * 0x0D]", create_start)
create_end = dialog.index(";", last_memcpy) + 1
create_text = dialog[create_start:create_end]
# The reference draws the tag UID from rand(); the tests feed it known bytes.
create_text = create_text.replace("rand()", "ref_rand_next()")

with open(out_path, "w", encoding="utf-8") as out:
    out.write("// Generated by tests/extract_ref.py - RPCS3 code, verbatim.\n\n")
    out.write(class_text + "\n")
    out.write("infinity_base g_infinitybase;\n\n")
    out.write(methods_text + "\n")
    out.write(crc_text + "\n")
    out.write(blank_decl + "\n\n")
    out.write(
        "static std::array<u8, 32> ref_process(u8* buf)\n{\n"
        "\tconst u8 command = buf[2];\n\tconst u8 sequence = buf[3];\n"
        "\tstd::array<u8, 32> q_result{};\n"
        "\t" + switch_text + "\n\treturn q_result;\n}\n\n"
    )
    out.write(
        "static bool ref_create_blank(u32 character, u8 series, std::array<u8, 0x14 * 0x10>& out)\n{\n"
        "\tfs::file inf_file(true);\n"
        + create_text.replace("return false;", "return false;")
        + "\n\tout = file_data;\n\treturn true;\n}\n"
    )
print("extracted:", len(class_text), len(methods_text), len(switch_text), len(crc_text), len(create_text))
