name: Build Flipper FAP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uFBT
        run: python3 -m pip install --upgrade ufbt
      - name: Build
        run: ufbt
      - name: Upload FAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ck42x_passvault-fap
          path: dist/ck42x_passvault.fap
