#!/usr/bin/env python3
"""Generate helpers/flipbip_xmr_words.c from tools/xmr_english.txt.

The list is Monero's English mnemonic word list (1626 words, as used by
monero-wallet-cli, Feather, Cake and Ledger's seedconv). It is sorted, so it
is stored front-coded and bit-packed, MSB first. Per word:

    4 bits  length of the prefix shared with the previous word (0..12)
    4 bits  number of new letters that follow (1..12)
    5 bits  per new letter, 'a' = 0 .. 'z' = 25

That is ~5.9 KB instead of ~11.5 KB for the plain strings (~18 KB with a
pointer table). Words are looked up by decoding from the start, which is
cheap enough for the 24 lookups done once per wallet load.

Usage: python3 tools/gen_xmr_wordlist.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "xmr_english.txt")
DST = os.path.join(HERE, "..", "helpers", "flipbip_xmr_words.c")

EXPECTED_WORDS = 1626
MAX_LEN = 12


def pack(words):
    bits = []

    def put(value, width):
        bits.extend((value >> (width - 1 - i)) & 1 for i in range(width))

    prev = ""
    for word in words:
        shared = 0
        while shared < min(len(word), len(prev)) and word[shared] == prev[shared]:
            shared += 1
        suffix = word[shared:]
        assert 1 <= len(suffix) <= MAX_LEN and shared <= MAX_LEN
        put(shared, 4)
        put(len(suffix), 4)
        for ch in suffix:
            put(ord(ch) - ord("a"), 5)
        prev = word

    bits.extend([0] * (-len(bits) % 8))
    return bytes(
        sum(bit << (7 - i) for i, bit in enumerate(bits[n : n + 8]))
        for n in range(0, len(bits), 8)
    )


def unpack(data, count):
    pos = 0

    def get(width):
        nonlocal pos
        value = 0
        for _ in range(width):
            value = (value << 1) | ((data[pos >> 3] >> (7 - (pos & 7))) & 1)
            pos += 1
        return value

    words, prev = [], ""
    for _ in range(count):
        shared, n = get(4), get(4)
        prev = prev[:shared] + "".join(chr(ord("a") + get(5)) for _ in range(n))
        words.append(prev)
    return words


def main():
    with open(SRC) as f:
        words = f.read().split()
    assert len(words) == EXPECTED_WORDS, len(words)
    assert words == sorted(words) and len(set(words)) == len(words)
    assert all(w.isascii() and w.isalpha() and w.islower() for w in words)
    assert max(map(len, words)) <= MAX_LEN

    data = pack(words)
    assert unpack(data, len(words)) == words

    rows = [
        "    " + " ".join(f"0x{b:02x}," for b in data[i : i + 12])
        for i in range(0, len(data), 12)
    ]
    with open(DST, "w") as f:
        f.write(
            "// Generated by tools/gen_xmr_wordlist.py from tools/xmr_english.txt.\n"
            "// Do not edit by hand.\n"
            "//\n"
            "// Monero English mnemonic word list (c) The Monero Project, BSD-3-Clause.\n"
            "// Front-coded and bit-packed; see the generator for the format.\n"
            "\n"
            '#include "flipbip_xmr_words.h"\n'
            "\n"
            f"const uint8_t FLIPBIP_XMR_WORDS_PACKED[{len(data)}] = {{\n"
            + "\n".join(rows)
            + "\n};\n"
        )
    print(f"{len(words)} words -> {len(data)} bytes, wrote {os.path.relpath(DST)}")


if __name__ == "__main__":
    main()
