name: Build MTools

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk-channel: [dev, release]
    steps:
      - uses: actions/checkout@v4
      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
