name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build FAP
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        with:
          sdk-channel: release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ear_trainer
          path: dist/*.fap
